apiVersion: v1
description: A dorothy runtime-bundle Helm chart for Kubernetes
icon: https://salaboy.files.wordpress.com/2018/01/acitiviti_icon_fullcolor_github_400x400.png
name: dorothy-workflow-rb
version: 0.0.1
