apiVersion: v1
description: A Helm chart for Activiti Cloud Connector
icon: "https://salaboy.files.wordpress.com/2018/01/acitiviti_icon_fullcolor_github_400x400.png"
name: sample-cloud-connector
version: 0.1.0
